[package]
name = "iryfful"
version = "0.1.0"
authors = ["Stéphane Campinas <stephane.campinas@gmail.com>"]

[dependencies]
failure = "0.1.1"
failure_derive = "0.1.1"

[dev-dependencies]
expectest = "0.9.2"
